# Generated by Django 3.2.4 on 2021-07-05 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet', models.TextField(verbose_name='Твит')),
                ('username', models.CharField(max_length=50, verbose_name='Автор')),
                ('like', models.IntegerField(verbose_name='Количество лайков')),
                ('dislike', models.IntegerField(verbose_name='Количество дизлайков')),
                ('nick', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ник')),
            ],
        ),
    ]
