# Generated by Django 3.2.4 on 2021-07-21 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitterbackend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='Имя')),
                ('telephone', models.IntegerField(verbose_name='Телефон')),
                ('password', models.TextField(verbose_name='Пароль')),
            ],
        ),
    ]
