# Generated by Django 3.2.4 on 2021-07-23 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitterbackend', '0002_regdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='regdata',
            old_name='telephone',
            new_name='phone',
        ),
    ]
